on:
  pull_request:
    branches: [ "master", "test", "test-merged-actions"]
    types:
      - closed

jobs:
 if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - run: |
          echo The PR was merged

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set mode to merge
        run: git config pull.rebase false

    # - uses: actions/setup-node@v3
    #   name: Use Node.js ${{ matrix.node-version }}
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci --force

    # - run: npm run build:designer-local
    #   name: Test if the build succeeds
    #   shell: bash
